# Generated by Django 5.1.2 on 2025-01-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='module',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
