# Generated by Django 5.1.2 on 2025-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0002_remove_enrollment_module_delete_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
